In [1]:
%matplotlib notebook
#For jupyter Notebook

In [2]:
#Libraries and Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import datetime

In [3]:
#point to the csv
file_to_load = 'IRAhandle_tweets_13.csv'
#read csv into a pandas dataframe
df_file = pd.read_csv(file_to_load)
df_file.head(2)

,external_author_id,author,content,region,language,publish_date,harvested_date,following,followers,updates,...,account_type,retweet,account_category,new_june_2018,alt_external_id,tweet_id,article_url,tco1_step1,tco2_step1,tco3_step1
0,2589513234,ZUBOVNIK,'@imerkouri 1) считать своих потенциальных изб...,Unknown,Russian,9/14/2015 7:57,9/14/2015 7:57,3563,22625,13188,...,Russian,0,NonEnglish,0,2589513234,643332738230165504,http://twitter.com/zubovnik/statuses/643332738...,NaN,NaN,NaN
1,2589513234,ZUBOVNIK,Европейское будущее оказалось не таким уж и сы...,Unknown,Russian,9/14/2015 8:18,9/14/2015 8:57,3563,22629,13193,...,Russian,0,NonEnglish,0,2589513234,643338084470403072,http://twitter.com/zubovnik/statuses/643338084...,https://twitter.com/zubovnik/status/6433380844...,NaN,NaN

In [4]:
df_data = pd.DataFrame(df_file[['tweet_id',
                   'external_author_id',
                   'author',
#                  'content',
#currently don't care about content
                   'region',
                   'language',
                   'publish_date',
                   'following',
                   'followers',
                   'account_type',
                   'retweet',
                   'account_category'
                  ]])
df_data.head()

,tweet_id,external_author_id,author,region,language,publish_date,following,followers,account_type,retweet,account_category
0,643332738230165504,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015 7:57,3563,22625,Russian,0,NonEnglish
1,643338084470403072,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015 8:18,3563,22629,Russian,0,NonEnglish
2,643346083121364992,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015 8:50,3563,22629,Russian,0,NonEnglish
3,643347984252538880,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015 8:58,3563,22629,Russian,0,NonEnglish
4,643355983222284288,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015 9:29,3563,22629,Russian,0,NonEnglish

In [5]:
df_data['publish_date'] = df_data['publish_date'].str.split(' ', expand=True)
df_data.head()

,tweet_id,external_author_id,author,region,language,publish_date,following,followers,account_type,retweet,account_category
0,643332738230165504,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015,3563,22625,Russian,0,NonEnglish
1,643338084470403072,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015,3563,22629,Russian,0,NonEnglish
2,643346083121364992,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015,3563,22629,Russian,0,NonEnglish
3,643347984252538880,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015,3563,22629,Russian,0,NonEnglish
4,643355983222284288,2589513234,ZUBOVNIK,Unknown,Russian,9/14/2015,3563,22629,Russian,0,NonEnglish

In [6]:
#I want to create a Column for election_timeframe
#Options being before, durring, and after
#The cutoff for before will be the February 1st 2016, the first day of primaries for 2016 election
#The cutoff for after will be after inauguration. January 20th 2017
df_data.loc[:,'publish_date'] = pd.to_datetime(df_data.loc[:,'publish_date'])
#gives an error, but stil evaluated. the publish_date column is now a pandas timestamp
before = (df_data['publish_date'] > pd.to_datetime('6/30/2015')) & (df_data['publish_date'] <= pd.to_datetime('3/1/2016')) 
during = (df_data['publish_date'] > pd.to_datetime('3/1/2016'))  & (df_data['publish_date'] <= pd.to_datetime('12/1/2016'))
after = (df_data['publish_date'] > pd.to_datetime('12/1/2016')) & (df_data['publish_date'] < pd.to_datetime('7/1/2017'))

df_data.loc[before, "time_period"] = 'Pre-election'
df_data.loc[during, "time_period"] = 'Election season'
df_data.loc[after, "time_period"] = 'Post-election'
df_data.head()

,tweet_id,external_author_id,author,region,language,publish_date,following,followers,account_type,retweet,account_category,time_period
0,643332738230165504,2589513234,ZUBOVNIK,Unknown,Russian,2015-09-14,3563,22625,Russian,0,NonEnglish,Pre-election
1,643338084470403072,2589513234,ZUBOVNIK,Unknown,Russian,2015-09-14,3563,22629,Russian,0,NonEnglish,Pre-election
2,643346083121364992,2589513234,ZUBOVNIK,Unknown,Russian,2015-09-14,3563,22629,Russian,0,NonEnglish,Pre-election
3,643347984252538880,2589513234,ZUBOVNIK,Unknown,Russian,2015-09-14,3563,22629,Russian,0,NonEnglish,Pre-election
4,643355983222284288,2589513234,ZUBOVNIK,Unknown,Russian,2015-09-14,3563,22629,Russian,0,NonEnglish,Pre-election

In [12]:
list_ = []
list_.append(df_data)
list_

[                 tweet_id  external_author_id           author   region  \
 0      643332738230165504          2589513234         ZUBOVNIK  Unknown
 1      643338084470403072          2589513234         ZUBOVNIK  Unknown
 2      643346083121364992          2589513234         ZUBOVNIK  Unknown
 3      643347984252538880          2589513234         ZUBOVNIK  Unknown
 4      643355983222284288          2589513234         ZUBOVNIK  Unknown
 5      776022981818585088          2589513234         ZUBOVNIK  Unknown
 6      908280886201856001          2589513234         ZUBOVNIK  Unknown
 7      643761679390670848          2589513234         ZUBOVNIK  Unknown
 8      643801815633555456          2589513234         ZUBOVNIK  Unknown
 9      643804809020243968          2589513234         ZUBOVNIK  Unknown
 10     643810631628550144          2589513234         ZUBOVNIK  Unknown
 11     643842467972968448          2589513234         ZUBOVNIK  Unknown
 12     643845691362668544          2589513234         ZUBOVNIK  Unknown
 13     643680510053621760          2589513234         ZUBOVNIK  Unknown
 14     643681751953473536          2589513234         ZUBOVNIK  Unknown
 15     643690420204126208          2589513234         ZUBOVNIK  Unknown
 16     643708527366795264          2589513234         ZUBOVNIK  Unknown
 17     643722747353407488          2589513234         ZUBOVNIK  Unknown
 18     776368459269738497          2589513234         ZUBOVNIK  Unknown
 19     776406637263204352          2589513234         ZUBOVNIK  Unknown
 20     776422905873694721          2589513234         ZUBOVNIK  Unknown
 21     776451445612654592          2589513234         ZUBOVNIK  Unknown
 22     776359288780517376          2589513234         ZUBOVNIK  Unknown
 23     644109865502289920          2589513234         ZUBOVNIK  Unknown
 24     644110328524091392          2589513234         ZUBOVNIK  Unknown
 25     644119535709196288          2589513234         ZUBOVNIK  Unknown
 26     644126272298328064          2589513234         ZUBOVNIK  Unknown
 27     644131459444436992          2589513234         ZUBOVNIK  Unknown
 28     644133389851828224          2589513234         ZUBOVNIK  Unknown
 29     644153247549259776          2589513234         ZUBOVNIK  Unknown
 ...                   ...                 ...              ...      ...
 20864  638885134566051840          3093873665  _YOUR_LIFESTYLE  Unknown
 20865  646640237427359749          3093873665  _YOUR_LIFESTYLE  Unknown
 20866  646685713870643200          3093873665  _YOUR_LIFESTYLE  Unknown
 20867  647425578807640065          3093873665  _YOUR_LIFESTYLE  Unknown
 20868  647499317117194241          3093873665  _YOUR_LIFESTYLE  Unknown
 20869  647516640217665536          3093873665  _YOUR_LIFESTYLE  Unknown
 20870  647847079788679168          3093873665  _YOUR_LIFESTYLE  Unknown
 20871  647868835547099136          3093873665  _YOUR_LIFESTYLE  Unknown
 20872  648890183891288065          3093873665  _YOUR_LIFESTYLE  Unknown
 20873  648920284796350464          3093873665  _YOUR_LIFESTYLE  Unknown
 20874  648967174015422464          3093873665  _YOUR_LIFESTYLE  Unknown
 20875  639248219277541376          3093873665  _YOUR_LIFESTYLE  Unknown
 20876  649295289942044672          3093873665  _YOUR_LIFESTYLE  Unknown
 20877  649308187443593217          3093873665  _YOUR_LIFESTYLE  Unknown
 20878  640236673528262656          3093873665  _YOUR_LIFESTYLE  Unknown
 20879  640238910946197504          3093873665  _YOUR_LIFESTYLE  Unknown
 20880  640243995092750336          3093873665  _YOUR_LIFESTYLE  Unknown
 20881  640289850625622018          3093873665  _YOUR_LIFESTYLE  Unknown
 20882  640555387997982720          3093873665  _YOUR_LIFESTYLE  Unknown
 20883  640330973926817792          3093873665  _YOUR_LIFESTYLE  Unknown
 20884  640630199684431872          3093873665  _YOUR_LIFESTYLE  Unknown
 20885  640404235285233664          3093873665  _YOUR_LIFESTYLE  Unknown
 20886  640857347816984576          3093873665  _YOUR_LIFESTYLE  Unknown
 20887  640917885334892544          3093873665  _YOUR_LIFESTYLE  Unknown
 20888  640699000002355200          3093873665  _YOUR_LIFESTYLE  Unknown
 20889  640698851108782080          3093873665  _YOUR_LIFESTYLE  Unknown
 20890  641262037654372352          3093873665  _YOUR_LIFESTYLE  Unknown
 20891  641685532263608320          3093873665  _YOUR_LIFESTYLE  Unknown
 20892  641739521793486849          3093873665  _YOUR_LIFESTYLE  Unknown
 20893  641525803604291584          3093873665  _YOUR_LIFESTYLE  Unknown

         language publish_date  following  followers account_type  retweet  \
 0        Russian   2015-09-14       3563      22625      Russian        0
 1        Russian   2015-09-14       3563      22629      Russian        0
 2        Russian   2015-09-14       3563      22629      Russian        0
 3        Russian   2015-09-14       3563      22629      Russian        0
 4        Russian   2015-09-14       3563      22629      Russian        0
 5        Russian   2016-09-14        655      26085      Russian        0
 6        Russian   2017-09-14        628      25218      Russian        0
 7        Russian   2015-09-15       3559      22640      Russian        0
 8      Ukrainian   2015-09-15       3559      22647      Russian        0
 9        Russian   2015-09-15       3559      22647      Russian        0
 10       Russian   2015-09-15       3559      22647      Russian        0
 11       English   2015-09-15       3559      22650      Russian        0
 12       English   2015-09-15       3559      22650      Russian        0
 13     Ukrainian   2015-09-15       3560      22634      Russian        0
 14       Russian   2015-09-15       3560      22634      Russian        0
 15       Russian   2015-09-15       3560      22634      Russian        0
 16       Russian   2015-09-15       3560      22636      Russian        0
 17       Russian   2015-09-15       3560      22639      Russian        0
 18       Serbian   2016-09-15        655      26079      Russian        0
 19       Russian   2016-09-15        655      26077      Russian        0
 20       Russian   2016-09-15        655      26078      Russian        0
 21       Russian   2016-09-15        655      26078      Russian        0
 22       Russian   2016-09-15        655      26079      Russian        0
 23       Russian   2015-09-16       3567      22713      Russian        0
 24       Russian   2015-09-16       3567      22713      Russian        0
 25       Russian   2015-09-16       3567      22715      Russian        0
 26       Russian   2015-09-16       3567      22715      Russian        0
 27       Russian   2015-09-16       3567      22715      Russian        0
 28       Russian   2015-09-16       3567      22715      Russian        1
 29       Russian   2015-09-16       3567      22717      Russian        0
 ...          ...          ...        ...        ...          ...      ...
 20864    Russian   2015-09-02         60          4      Russian        0
 20865  Ukrainian   2015-09-23         60          8      Russian        0
 20866  Bulgarian   2015-09-23         60          8      Russian        0
 20867    Russian   2015-09-25         60          8      Russian        0
 20868    Russian   2015-09-25         60          8      Russian        0
 20869    Russian   2015-09-25         60          8      Russian        0
 20870  Bulgarian   2015-09-26         60          8      Russian        0
 20871    Russian   2015-09-26         60          8      Russian        0
 20872    Russian   2015-09-29         60          9      Russian        0
 20873    Russian   2015-09-29         60          9      Russian        0
 20874    Russian   2015-09-29         60          9      Russian        0
 20875    Russian   2015-09-03         60          4      Russian        0
 20876  Ukrainian   2015-09-30         60          9      Russian        0
 20877    Russian   2015-09-30         60          9      Russian        0
 20878    Serbian   2015-09-05         60          4      Russian        0
 20879  Ukrainian   2015-09-05         60          4      Russian        0
 20880    Russian   2015-09-05         60          4      Russian        0
 20881    Russian   2015-09-05         60          4      Russian        0
 20882    Russian   2015-09-06         60          4      Russian        0
 20883    Russian   2015-09-06         60          4      Russian        0
 20884  Bulgarian   2015-09-06         60          4      Russian        0
 20885  Ukrainian   2015-09-06         60          4      Russian        0
 20886  Ukrainian   2015-09-07         60          4      Russian        0
 20887    Russian   2015-09-07         60          4      Russian        0
 20888    Russian   2015-09-07         60          4      Russian        0
 20889      Uzbek   2015-09-07         60          4      Russian        0
 20890    Russian   2015-09-08         60          4      Russian        0
 20891    Russian   2015-09-09         60          4      Russian        0
 20892    Russian   2015-09-09         60          4      Russian        0
 20893    Russian   2015-09-09         60          4      Russian        0

       account_category      time_period
 0           NonEnglish     Pre-election
 1           NonEnglish     Pre-election
 2           NonEnglish     Pre-election
 3           NonEnglish     Pre-election
 4           NonEnglish     Pre-election
 5           NonEnglish  Election season
 6           NonEnglish              NaN
 7           NonEnglish     Pre-election
 8           NonEnglish     Pre-election
 9           NonEnglish     Pre-election
 10          NonEnglish     Pre-election
 11          NonEnglish     Pre-election
 12          NonEnglish     Pre-election
 13          NonEnglish     Pre-election
 14          NonEnglish     Pre-election
 15          NonEnglish     Pre-election
 16          NonEnglish     Pre-election
 17          NonEnglish     Pre-election
 18          NonEnglish  Election season
 19          NonEnglish  Election season
 20          NonEnglish  Election season
 21          NonEnglish  Election season
 22          NonEnglish  Election season
 23          NonEnglish     Pre-election
 24          NonEnglish     Pre-election
 25          NonEnglish     Pre-election
 26          NonEnglish     Pre-election
 27          NonEnglish     Pre-election
 28          NonEnglish     Pre-election
 29          NonEnglish     Pre-election
 ...                ...              ...
 20864       NonEnglish     Pre-election
 20865       NonEnglish     Pre-election
 20866       NonEnglish     Pre-election
 20867       NonEnglish     Pre-election
 20868       NonEnglish     Pre-election
 20869       NonEnglish     Pre-election
 20870       NonEnglish     Pre-election
 20871       NonEnglish     Pre-election
 20872       NonEnglish     Pre-election
 20873       NonEnglish     Pre-election
 20874       NonEnglish     Pre-election
 20875       NonEnglish     Pre-election
 20876       NonEnglish     Pre-election
 20877       NonEnglish     Pre-election
 20878       NonEnglish     Pre-election
 20879       NonEnglish     Pre-election
 20880       NonEnglish     Pre-election
 20881       NonEnglish     Pre-election
 20882       NonEnglish     Pre-election
 20883       NonEnglish     Pre-election
 20884       NonEnglish     Pre-election
 20885       NonEnglish     Pre-election
 20886       NonEnglish     Pre-election
 20887       NonEnglish     Pre-election
 20888       NonEnglish     Pre-election
 20889       NonEnglish     Pre-election
 20890       NonEnglish     Pre-election
 20891       NonEnglish     Pre-election
 20892       NonEnglish     Pre-election
 20893       NonEnglish     Pre-election

 [20894 rows x 12 columns]]